[features]
seeds = false
skip-lint = false
[programs.localnet]
solanapdas = "ENj3Q9wVayvVqRATojojAxSwKrqJ2gw2jehm3VqudKfp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
